In [2]:
import math
import numpy as np
import pandas as pd
import yfinance as yf

In [3]:
# Get the list of all companies on the S&P500 that have been publicly traded since 2005

table=pd.read_html('https://en.wikipedia.org/wiki/List_of_S%26P_500_companies')
df = table[0]
df.head()

df['date_added_clean'] = df['Date first added'].str.split(' ').str[0]
df["date_added_clean"] = pd.to_datetime(df['date_added_clean'] , format='%Y-%m-%d')
df = df[df["date_added_clean"] <= "2005-01-01"]

cols = list(df["Symbol"].unique())

In [4]:
data = yf.download(
        # tickers list or string as well
        tickers = cols,

        # use "period" instead of start/end
        # valid periods: 1d,5d,1mo,3mo,6mo,1y,2y,5y,10y,ytd,max
        # (optional, default is '1mo')
        period = "max",

        # fetch data by interval (including intraday if period < 60 days)
        # valid intervals: 1m,2m,5m,15m,30m,60m,90m,1h,1d,5d,1wk,1mo,3mo
        # (optional, default is '1d')
        interval = "1d",

        # group by ticker (to access via data['SPY'])
        # (optional, default is 'column')
        group_by = 'column',

        # adjust all OHLC automatically
        # (optional, default is False)
        auto_adjust = True,

        # download pre/post regular market hours data
        # (optional, default is False)
        prepost = True,

        # use threads for mass downloading? (True/False/Integer)
        # (optional, default is True)
        threads = True,

        # proxy URL scheme use use when downloading?
        # (optional, default is None)
        proxy = None
    )

[*********************100%***********************]  196 of 196 completed

1 Failed download:
- BF.B: 1d data not available for startTime=-2208988800 and endTime=1634800420. Only 100 years worth of day granularity data are allowed to be fetched per request.

In [5]:
dailydata = data["2005-01-01":]["Close"]

In [6]:
for col in list(dailydata.columns):
    if math.isnan(dailydata.loc['2005-01-03', col]):
        dailydata = dailydata.drop(col,axis=1)
        print(f"DROPPING {col}")

DROPPING BF.B
DROPPING HWM

In [7]:
dailydata

,A,AAPL,ABC,ABT,ADBE,ADI,ADM,ADP,ADSK,AEE,...,WBA,WFC,WMB,WMT,XEL,XLNX,XOM,YUM,ZBH,ZION
Date,,,,,,,,,,,,,,,,,,,,,
2005-01-03,14.709121,0.970390,11.445737,14.899008,30.838949,24.181890,14.927084,23.166319,37.410706,23.729563,...,28.672253,19.269854,6.406215,37.173866,9.507133,20.810459,29.058706,12.369188,73.068871,52.221573
2005-01-04,14.321063,0.980356,11.355198,14.748964,30.024111,23.524029,14.763943,22.796507,34.981960,23.541504,...,28.466324,19.285421,6.352588,37.083279,9.364684,20.220350,28.861469,12.205393,73.041267,51.508644
2005-01-05,14.314906,0.988943,11.333548,14.579760,29.859142,23.630358,14.512438,22.701406,35.251820,23.329330,...,29.197695,19.307215,6.307214,37.132065,9.259167,19.580462,28.710636,12.176337,72.470558,51.322666
2005-01-06,14.000765,0.989709,11.429995,14.908585,29.364239,23.590483,14.811520,22.548201,35.081905,23.565611,...,29.211899,19.375687,6.393839,37.661617,9.243341,19.267637,29.076105,12.313711,73.308235,51.617115
2005-01-07,13.988448,1.061771,11.396534,15.163980,29.384233,23.623711,14.845518,22.505934,34.282318,23.555969,...,29.467503,19.350788,6.323713,37.619804,9.190579,19.431158,28.884680,12.245017,73.179337,50.361752
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-10-14,152.589996,143.759995,120.110001,117.570000,607.510010,168.199997,64.169998,208.520004,289.170013,83.900002,...,50.770000,45.310001,29.370001,139.869995,65.430000,165.809998,62.000000,125.050003,145.630005,62.639999
2021-10-15,153.270004,144.839996,119.860001,117.489998,610.090027,172.039993,63.950001,212.979996,291.190002,83.180000,...,48.919998,48.380001,29.549999,140.550003,65.930000,167.149994,62.590000,125.209999,146.360001,62.139999
2021-10-18,154.779999,146.550003,118.379997,116.820000,622.830017,173.330002,63.799999,212.570007,292.670013,82.680000,...,48.400002,49.430000,29.290001,141.679993,64.680000,170.389999,62.560001,126.449997,144.970001,62.230000
2021-10-19,155.619995,148.759995,119.839996,119.339996,636.070007,176.630005,64.540001,213.979996,296.690002,83.510002,...,48.009998,50.340000,29.000000,144.690002,64.930000,170.240005,63.500000,125.709999,148.919998,63.250000
2021-10-20,157.589996,149.259995,122.250000,123.309998,632.369995,176.919998,64.839996,213.050003,298.640015,84.349998,...,48.389999,50.160000,29.160000,146.000000,65.570000,170.369995,63.849998,125.879997,150.130005,65.099998

In [8]:
dailydata.to_csv("data/adjclose.csv")